#!/usr/bin/env python3
from pathlib import Path
root = Path(__file__).resolve().parents[1]
host = (root / "integration/overlay/src/Jampanion.Web/wwwroot/js/jazz-chart-host.js").read_text()
logic = (root / "integration/overlay/src/Jampanion.Web/Pages/IntegratedHomeLogic.cs").read_text()
planner = (root / "integration/overlay/src/Jampanion.Web/Audio/IntegratedSessionPlanner.cs").read_text()
home = (root / "integration/overlay/src/Jampanion.Web/Pages/Home.razor").read_text()
css = (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text()
customize_viewer = (root / "scripts/customize-viewer.mjs").read_text()
style_change_method = logic[logic.find('protected async Task ChangeStyleAsync'):logic.find('private static int DefaultTempoForStyle')]
tempo_change_method = logic[logic.find('private async Task RebuildLiveTempoAsync'):logic.find('private async Task QueueStyleChangeAsync')]

checks = {
    "playback disables original search": 'search.disabled = playing' in host,
    "stopping clears search loading state": 'search.removeAttribute("aria-busy")' in host and 'if (playing)' in host,
    "playback locks selected song": 'playbackLockedSongId' in host,
    "embedded Space forwards to parent": 'name: "spaceShortcut"' in host,
    "Space shortcut ignores interactive controls": 'shortcutBelongsToInteractiveControl' in host and 'tag === "button"' in host and '.search-options' in host,
    "native iReal can restore original": 'viewer.parseIRealCollection' in host and 'originalSourceRecord' in host,
    "3/4 style menu is constrained": 'resolvedMeterAt(song.bars || [], sourceIndex) === "3/4"' in host,
    "empty edit removes a chord": 'bar.chordSlots.splice(slotIndex, 1)' in host,
    "jumped repeat context uses written bars": 'const priorTwo = sourceIndex > 1 ? resolveWrittenChords(sourceIndex - 2) : []' in host and 'const previous = prior.at(-1)?.symbol || "N.C."' in host,
    "playback uses one canonical expansion": 'function buildCanonicalPlaybackSequence' in host and 'return buildCanonicalPlaybackSequence(loopSource, sourceOffset, expandChartBars);' in host and 'const expanded = buildCanonicalPlaybackSequence(loopSource, sourceOffset, expandChartBars);' in host,
    "iReal player style precedes chart inference": 'stored.accompanimentStyle || sourcePlayerStyle || inferredStyle(song)' in host,
    "subbeat duration sees all chord changes": '.Where(candidate => candidate.StartTick > change.StartTick)' in planner,
    "old harmony is truncated at offbeat change": 'TruncateHarmonyAtTick(notes, exactTick)' in planner,
    "waltz count-in includes beat two": 'beatsPerBar == 4 && bar == 0 && beat % 2 != 0' in planner,
    "playback uses Viewer-rendered normalized grid": 'captureSourceTiming' in host and 'dataset.gridStart' in host and 'gridCellToTick(start, total, activeMeter)' in host,
    "start locks chart before compilation": logic.find('InvokeVoidAsync("setPlaybackState", true, -1)') < logic.find('InvokeAsync<JazzPlaybackFormDto>("compilePlayback")'),
    "start failure stops audio": 'await startedAudio.InvokeVoidAsync("stopSession")' in logic,
    "start preparation is cancelable": 'generationVersion != _generationVersion' in logic and 'await Task.Yield();' in logic and '@(!IsPlaying && !IsLoading)' in home,
    "style changes use four-bar boundary": 'SequenceIndex % SessionConstants.BarsPerSegment == 0' in logic,
    "style continuation is replaced, not rebased immediately": '"replaceContinuation"' in logic,
    "style changes preserve the current tempo": 'TempoBpm = DefaultTempoForStyle(SelectedStyle)' not in style_change_method,
    "tempo changes wait for a bar boundary": 'NextBarBoundary' in tempo_change_method and 'next bar boundary' in tempo_change_method,
    "same tempo does not create a dirty state": 'if (requested == TempoBpm)' in logic and 'do not turn an Auto/default' in logic,
    "tempo continuation is replaced without rebasing": '"replaceContinuation"' in tempo_change_method and '"replaceSession"' not in tempo_change_method,
    "Ending appends the native final tonic hold": 'EndingPlanBuilder.Build' in planner and 'headOutRendered = true' in planner and 'Ending / final tonic' in planner,
    "Ending retains the root-hold plan inputs": 'headOutExactTune.TonicChord' in planner and 'endingPlan.LengthTicks' in planner,
    "all edits share one explicit save": 'SaveAccompanimentSettingsAsync' in logic and 'HasUnsavedChanges' in logic and 'saveCurrentChart' in logic and 'SaveSongSettingsAsync' in logic,
    "Save refreshes delayed key state": 'InvokeAsync<JazzChartBootstrap>("getState")' in logic and 'Refresh immediately before the dirty check' in logic and 'if (!HasUnsavedChanges || string.IsNullOrWhiteSpace(SelectedIdentity)) return;' in logic,
    "mobile controls are separated from the mix": 'jamp-mobile-controls' in home and 'position:fixed; top:0; left:0; right:0; z-index:30; order:1;' in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text() and '.mix-panel { order:3;' in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text(),
    "mobile controls stay compact": 'height:56px' in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text() and 'height:50px' in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text(),
    "integrated brand row has icon and text only": '<img src="icons/jampanion-32.png' in home and '<strong>Jampanion2</strong>' in home and 'jamp-brand-actions' not in home,
    "desktop brand row is above session": '.jamp-brand-row { order:-1; align-self:center; margin-top:0;' in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text(),
    "startup brand is customized": 'customize-shell.mjs' in (root / "scripts/build-integrated.sh").read_text() and 'Jampanion2' in (root / "scripts/customize-shell.mjs").read_text(),
    "cache-busted page versions": 'APP_VERSION = "31"' in (root / "scripts/customize-shell.mjs").read_text() and 'help.html?v=31' in (root / "scripts/customize-viewer.mjs").read_text() and 'help.en.html?v=31' in (root / "scripts/customize-viewer.mjs").read_text() and 'jazz-chart-host.js?v=34' in (root / "scripts/customize-viewer.mjs").read_text() and 'help.css?v=31' in (root / "scripts/customize-help.mjs").read_text() and 'jazz-chart-host.js?v=46' in logic and 'viewer/index.html?integrated=14' in home,
    "English Jampanion help is built": 'customize-help-en.mjs' in (root / "scripts/build-integrated.sh").read_text() and 'test-help-en-contract.mjs' in (root / "scripts/build-integrated.sh").read_text(),
    "transpose is saved with accompaniment settings": 'CurrentSemitoneShift' in logic and 'SemitoneShift' in (root / "integration/overlay/src/Jampanion.Web/Models/JazzChartModels.cs").read_text() and 'semitoneShift' in host and 'saveSongSettings' in logic,
    "standalone viewer Save includes settings": 'installStandaloneSaveButton' in host and 'jampanionStandaloneSave' in host and 'window.parent !== window' in host and 'hasUnsavedStandaloneSettings' in host and 'Save chart, key, tempo, and style' in host and 'Number(viewer.state.semitones) || 0' in host and 'toolbarHasUnsavedChanges' in host,
    "Viewer toolbar actions stay compact": '.utility-group .standalone-save' in host and 'justify-content:center' in host and 'flex:0 0 auto' in host and 'width:auto' in host,
    "viewer toolbar keeps Revert for saved overrides": 'jampanionStandaloneRevert' in host and 'toolbarRevertVisible' in host and 'standaloneRevertButton.hidden = !toolbarRevertVisible' in host and 'revertButton.textContent = "Revert"' in host and 'setToolbarState' in host and 'CurrentSongHasSavedOverrides' in logic,
    "rehearsal marks use double-click editing": 'const lead = event.target.closest?.(".system-lead")' in host and 'editRehearsal(sourceIndex, lead)' in host,
    "rehearsal editing is limited to the upper bar band": 'function isRehearsalEditPoint(event, bar)' in host and 'isRehearsalEditPoint(event, firstBar)' in host and 'isRehearsalEditPoint(event, bar)' in host,
    "rehearsal editor size is consistent": 'anchor?.classList?.contains?.("bar")' in host and 'isRehearsal ? 64' in host and 'const height = isChord ? rect.height : 28' in host,
    "rehearsal context menu only sets styles": 'bar.section = label || null' in host and 'Add rehearsal mark' not in host and 'Edit rehearsal mark' not in host and 'Remove rehearsal mark' not in host and 'Section style:' in host,
    "head out leaves queued state when active": 'HeadOutActive' in logic and 'HeadOutQueued = false;' in logic and 'stage.Name, "HeadOut"' in logic,
    "head out completion rerenders after automatic stop": 'position >= _sessionPlan.DurationSeconds + 0.3d' in logic and 'await StopSessionAsync();\n                    await InvokeAsync(StateHasChanged);' in logic,
    "viewer toolbar owns all chart actions": 'SaveChartFromToolbar' in logic and 'RevertChartFromToolbar' in logic and 'toolbarSave' in host and 'toolbarRevert' in host and 'fitButton.after(newButton, button, revertButton)' in host and 'toolbarNew' in host and 'NewSongFromToolbar' in logic,
    "integrated brand row has no duplicate actions": 'jamp-brand-actions' not in home and 'standaloneSaveButton.disabled = !editingEnabled || !song || !hasChanges' in host and 'setToolbarState' in logic,
    "mobile control order and conditional fade": 'session-panel { order:1' in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text() and 'label + label { order:3' in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text() and 'can-scroll-left' in host and 'can-scroll-right' in host,
    "mobile session frame and field captions are removed": 'border:0; border-radius:0; background:transparent; padding:0;' in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text() and '.compact-fields span { display:none; }' in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text() and 'aria-label="Tempo"' in home and 'aria-label="Style"' in home,
    "mobile Mix fits inside the viewport": 'height:58px; max-height:58px; min-height:0; overflow:hidden;' in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text(),
    "narrow mobile Mix keeps all channels visible": '@media (max-width:350px)' in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text() and 'repeat(4,minmax(56px,1fr))' in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text(),
    "mobile browser chrome can collapse": 'html, body { height:auto; min-height:100%; overflow-x:hidden; overflow-y:auto; }' in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text() and '#app { height:auto; min-height:calc(100dvh + 1px); overflow:visible; }' in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text(),
    "mobile controls align and match chart row": 'padding:3px 6px' in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text() and 'height:30px; min-height:30px' in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text() and '.jamp-mobile-controls .tiny { border-radius:5px; }' in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text() and 'session-controls button { height:30px!important; min-height:30px!important; max-height:30px;' in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text() and '.session-panel { width:166px; height:50px; }' in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text() and '.jamp-brand-row { order:4; align-self:center; flex:0 0 36px; width:max-content; height:36px;' in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text() and '.jamp-brand-row strong { display:block; font-size:12px; }' in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text() and 'initializeMobileControlsScrollHint' in logic,
    "mobile brand is below Mix": home.find('<section class="jamp-panel mix-panel">') < home.find('<section class="jamp-brand-row">'),
    "mobile playback keeps controls available": '.jamp-shell.is-playing .jamp-brand-row { display:none; }' not in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text() and '.jamp-shell.is-playing .accompaniment-panel { display:none; }' not in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text() and '.jamp-shell.is-playing .jamp-mobile-controls { overflow:hidden; }' not in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text(),
    "mobile playback scrolls the active bar": 'scrollPlaybackTarget(target)' in host and 'const embeddedMobile = mobile && window.parent !== window;' in host and 'if (!embeddedMobile)' in host and 'window.parent.scrollBy' in host and 'usableHeight' in host and '0.075' in host and 'Math.abs(delta) > 12' in host,
    "last selected song is remembered and restored": 'LAST_SONG_KEY' in host and 'rememberSelectedSong' in host and 'restoreLastSelectedSong' in host and 'songIdentity(song)' in host and 'fallback until the saved song appears' in host,
    "section style is shown above rehearsal marks": 'jamp-section-style' in host and 'sectionStyleAbbreviation' in host and 'case "Swing": return "Swing"' in host and 'case "JazzBallad": return "Ballad"' in host and 'case "BossaNova": return "Bossa"' in host and 'case "AfroCubanLatin": return "Latin"' in host and 'case "JazzWaltz": return "Waltz"' in host and 'current?.remove()' in host and 'badge.textContent !== styleLabel' in host and 'commonSectionStyleBadgeFontSize' in host and 'fitSectionStyleBadge(badge, lead, commonFontSize)' in host and 'lead.querySelector(".rehearsal-mark")' in host and 'badge.offsetWidth' in host and 'badge.style.maxWidth' in host and 'overflow:visible' in host and 'position:absolute; z-index:8; left:0; top:-18px;' in host and 'font:700 16px/16px Arial' in host,
    "embedded chart viewport stays within its frame": 'body.jampanion-embedded .chart-viewport' in host and 'min-width:0 !important;' in host and 'height:auto !important;' in host,
    "mobile chart expands into the parent scroll": 'name: "layoutChanged"' in host and 'installEmbeddedLayoutObserver' in host and 'embeddedLayoutMutationObserver' in host and 'toolbarHeight + chartHeight' in host and 'body.jampanion-embedded .chart-viewport' in host and 'height:auto; min-height:0; overflow:visible;' in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text(),
    "Stop is the only session stop control": 'StopSessionAsync' in home and 'Panic' not in home and 'InvokeVoidAsync("stopSession")' in logic,
    "session status is omitted": 'session-status' not in home and 'Stopped' not in home and '0:00' not in home,
    "visible footer status is omitted": 'jamp-footer-status' not in home and 'jamp-footer-status' not in (root / "integration/overlay/src/Jampanion.Web/wwwroot/css/jazz-integration.css").read_text(),
    "tempo Auto control is removed": 'ResetTempoAutoAsync' not in logic and '>Auto<' not in home,
    "tempo spinner advances by five": 'step="5"' in home,
    "MIDI preferences persist": 'saveDevicePreferences' in host and 'getDevicePreferences' in logic,
    "MIDI Thru restores saved input": 'RestorePreferredInputForMidiThruAsync' in logic,
    "Built-in Trio remains usable without Web MIDI": 'Built-in Trio available · Web MIDI unavailable' in logic,
    "MIDI Settings guard unsupported browsers": 'typeof navigator !== \'undefined\' && typeof navigator.requestMIDIAccess === \'function\'' in logic and 'SetMidiUnavailableStatus' in logic and 'disabled="@MidiUnavailable"' in home,
    "tempo rollback preserves Auto/manual state": 'previousTempoExplicit' in logic and 'previousTempoUserSet' in logic,
    "bootstrap ignores cross-song changes during playback": 'Stop the session before changing songs' in logic,
    "chart editing survives viewer re-render": 'doc.addEventListener("dblclick", handleDoubleClick, true)' in host and 'observer.observe(doc, { childList: true, subtree: true })' in host,
    "song selection reapplies saved transpose": 'Reapply the per-song saved key' in host and 'const restored = restoreStoredTranspose();' in host and 'if (restored) queueBootstrapNotification();' in host,
    "Viewer selection does not clear transpose": 'JAMPANION_SELECTION_TRANSPOSE_V1' in customize_viewer and 'const newSelectSong = `function selectSong(songId) {' in customize_viewer and '  state.searchOpen = false;' in customize_viewer,
    "Revert asks for concise confirmation": 'window.confirm("Revert saved changes?")' in host and 'export async function revertCurrentSong()' in host,
    "title editor stays inside the title box": 'openTitleEditor(anchor, value, commit)' in host and '.score-header h1 .jamp-title-edit-input' in host and 'anchor.replaceChildren(input)' in host,
    "no-op rehearsal and style edits do not enable Save": 'const nextSection = label || null' in host and 'const nextStyle = value || null' in host and 'setToolbarState(true, true)' in host,
    "disabled Save is visibly and pointer-disabled": '.standalone-save:disabled' in host and 'pointer-events:none' in host and 'background:#edf0f1' in host,
    "Save label does not cause layout shift": 'button.textContent = "Saved"' not in host and 'SaveButtonText' not in logic and 'ShowSaveConfirmationAsync' not in logic,
    "mode switching uses matching-weight Viewer Mode link": 'jamp-mode-row' in home and '>Viewer Mode<' in home and 'jampanion-viewer.png' in home and '.jamp-mode-row img { width:22px; height:22px;' in css and 'font-size:15px; font-weight:400;' in css and '.jamp-mode-row a { font-size:12px; font-weight:400; }' in css and 'installStandaloneModeLink' in host and 'jampanion-viewer.png' in (root / "scripts/customize-viewer.mjs").read_text() and 'jampanion-mode-link' in host,
    "embedded startup waits for saved song": 'viewer.libraryReady' in host and 'await loadNativeSongs()' in host and 'jampanion-startup-pending' in host and 'libraryReady' in (root / "scripts/test-viewer-contract.mjs").read_text() and 'Loading saved song' in (root / "scripts/customize-viewer.mjs").read_text() and 'using demo fallback' in (root / "scripts/customize-viewer.mjs").read_text(),
    "delete-all clears Jampanion restore state": 'jampanion-library-cleared' in (root / "scripts/customize-viewer.mjs").read_text() and 'handleLibraryCleared' in host and 'removeSongSettings(identity)' in host and 'localStorage.removeItem(LAST_SONG_KEY)' in host,
    "customized songs keep normal title typography": '.jampanion-customized-title' in host and 'color:inherit' in host and 'font-size:inherit' in host and 'font-weight:inherit' in host,
    "customized songs restore original imports": 'annotateSongOptions' in host and 'jampanion-customized-marker' in host and 'updateCustomizedSearchTitle' in host and 'deleteCustomizedSongs' in host and 'restoreSongsByIds' in host and 'will be kept' in host and 'restoreSongsByIds' in (root / "scripts/customize-viewer.mjs").read_text(),
    "background playback does not stop on page visibility": 'visibilityHandler' not in host and 'StopSessionFromVisibility' not in host and 'customize-background-playback.mjs' in (root / "scripts/build-integrated.sh").read_text() and 'jampanion-audio.js?v=30' in logic,
    "blank chord cells add at the clicked beat": 'A rendered chord slot can span several empty beat cells' in host and 'first?.classList.contains("cell-positioned-slot")' in host and 'const maxInputCells = meter === "3/4" ? 3 : 4' in host and 'Math.min(maxInputCells, Math.max(1, renderedTotal || maxInputCells))' in host and 'openEditorAtPoint(inputLeft' in host and 'const sourceCell = hasVisibleSlot ? insertCell : startCell' in host and 'hidden: true' in host,
    "existing chord double-click opens its value": 'const clickedChord = event.target.closest?.(".chord")' in host and 'editChord(sourceIndex, clickedSlotIndex, clickedChordSlot)' in host,
    "new chord input divisions are capped at bar beats": 'const maxInputCells = meter === "3/4" ? 3 : 4' in host and 'Math.min(maxInputCells, Math.max(1, renderedTotal || maxInputCells))' in host,
    "double-click beat wins over long chord text": 'const clickedBar = event.target.closest?.(".bar:not(.spacer)")' in host and 'if (Number.isInteger(sourceIndex) && grid.startCell > 0)' in host and 'addChordAtPoint(sourceIndex, clickedBar, event.clientX)' in host,
    "chart edits require an explicit save": 'HasUnsavedChartChanges' in logic and 'saveCurrentChart' in host and 'stageNative(song)' in host,
    "mixer preferences persist": 'saveMixerPreferences' in logic and 'getMixerPreferences' in logic and 'MIXER_SETTINGS_KEY' in host,
}
failed = [name for name, ok in checks.items() if not ok]
if failed:
    raise SystemExit("Integration invariant failures:\n- " + "\n- ".join(failed))
print(f"Integration invariant checks passed ({len(checks)} checks).")
